from src.company_item import CompanyItem


def get_company_list() -> []:
    return [CompanyItem("kraken", "https://jobs.lever.co/kraken", "https://kraken.com", "Exchange"),
            CompanyItem("chainlink", "https://jobs.lever.co/chainlink", "https://chain.link",
                        "Blockchain"),
            CompanyItem('ethglobal', 'https://jobs.lever.co/ETHGlobal', 'https://ethglobal.com',
                        'Community'),
            CompanyItem("chainstack", "https://chainstack.bamboohr.com/jobs",
                        "https://chainstack.com", "Infra"),
            CompanyItem('multiversx', 'https://jobs.lever.co/multiversx', 'https://multiversx.com',
                        'Blockchain'),
            CompanyItem("tessera", "https://jobs.lever.co/ftc",
                        "https://tessera.co", "NFT"),
            CompanyItem('axiomzen', 'https://jobs.lever.co/axiomzen',
                        'https://www.axiomzen.com', 'Web3'),
            CompanyItem("paxos", "https://paxos.com/careers/role", "https://paxos.com",
                        "Stable Coin"),
            CompanyItem("zora", "https://boards.greenhouse.io/zora",
                        "https://zora.co", "NFT"),
            CompanyItem('fuellabs', 'https://jobs.lever.co/fuellabs', 'https://www.fuel.network',
                        'Blockchain'),
            CompanyItem('harmony', 'https://jobs.lever.co/harmony', 'https://www.harmony.one',
                        'Blockchain'),
            CompanyItem('wintermute', 'https://jobs.lever.co/wintermute-trading',
                        'https://www.wintermute.com',
                        'Trading'),
            CompanyItem("bitcoin", "https://www.bitcoin.com/jobs/#joblist",
                        "https://www.bitcoin.com", 'Exchange'),
            CompanyItem("cexio", "https://cexio.bamboohr.com/jobs",
                        "https://cex.io", "Exchange"),
            CompanyItem("circle", "https://boards.greenhouse.io/circle", "https://circle.com",
                        "Stable Coin"),
            CompanyItem("status", "https://jobs.status.im",
                        "https://status.im", "Messanger"),
            CompanyItem("OKX", "https://boards.greenhouse.io/OKX", "https://okx.com",
                        "Exchange"),
            CompanyItem("bittrex", "https://boards.greenhouse.io/bittrex",
                        "https://global.bittrex.com", 'Exchange'),
            CompanyItem("kaiko", "https://jobs.eu.lever.co/kaiko",
                        "https://www.kaiko.com", "Data"),
            CompanyItem("bitmex", "https://boards.greenhouse.io/bitmex", "https://bitmex.com",
                        "Exchange"),
            CompanyItem("bitgo", "https://boards.greenhouse.io/bitgo", "https://bitgo.com",
                        "Exchange"),
            CompanyItem("bitpanda", "https://boards.eu.greenhouse.io/bitpanda",
                        "https://bitpanda.com", "Exchange"),
            CompanyItem("uniswaplabs", "https://boards.greenhouse.io/uniswaplabs",
                        "https://uniswap.org", "Exchange Protocol"),
            CompanyItem("moonpay", "https://boards.greenhouse.io/moonpay",
                        "https://www.moonpay.com", "Payments"),
            CompanyItem("moonwalk", "https://boards.greenhouse.io/moonwalk",
                        "https://www.moonwalk.com", "Platform"),
            CompanyItem("blockdaemon", "https://boards.greenhouse.io/blockdaemon",
                        "https://www.blockdaemon.com", "Staking & Infra"),
            CompanyItem("figment", "https://boards.greenhouse.io/figment",
                        "https://www.figment.io", "Staking & Infra"),
            CompanyItem("quiknodeinc", "https://boards.greenhouse.io/quiknodeinc",
                        "https://www.quicknode.com", "Staking & Infra"),
            CompanyItem("genesisglobaltradinginc", "https://boards.greenhouse.io/genesisglobaltradinginc",
                        "https://genesistrading.com", "OTC Trading"),
            CompanyItem("amun", "https://boards.greenhouse.io/amun",
                        "https://www.21.co", "OTC"),
            CompanyItem("exodus54", "https://boards.greenhouse.io/exodus54",
                        "https://www.exodus.com", "Wallet"),
            CompanyItem("alchemy", "https://boards.greenhouse.io/alchemy",
                        "https://www.alchemy.com", "Dev & Infra"),
            CompanyItem("chainalysis", "https://boards.greenhouse.io/chainalysis",
                        "https://www.chainalysis.com", "Crypto Research"),
            CompanyItem("magiceden", "https://boards.greenhouse.io/magiceden",
                        "https://www.magiceden.io", "NFT"),
            CompanyItem("aztec", "https://boards.eu.greenhouse.io/aztec",
                        "https://aztec.network", "Protocol"),
            CompanyItem("nethermind", "https://boards.eu.greenhouse.io/nethermind",
                        "https://nethermind.io", "Crypto software"),
            CompanyItem("dfinity", "https://boards.greenhouse.io/dfinity",  "https://dfinity.org",
                        "Blockchain"),
            CompanyItem('stellar', 'https://boards.greenhouse.io/stellar',
                        'https://stellar.org', 'Blockchain'),
            CompanyItem("parity", "https://boards.greenhouse.io/parity",  "https://www.parity.io",
                        "Infra"),
            CompanyItem("optimism", "https://boards.greenhouse.io/optimism",
                        "https://www.optimism.io", "L2 protocol"),
            CompanyItem('bebop', 'https://jobs.lever.co/Bebop',
                        'https://bebop.xyz', 'DeFi Exchange'),
            CompanyItem("flashbots", "https://boards.greenhouse.io/flashbots",
                        "https://www.flashbots.net", "ETH MEV"),
            CompanyItem("oplabs", "https://boards.greenhouse.io/oplabs",  "https://www.oplabs.co",
                        "L2 protocol"),
            CompanyItem("bitfinex", "https://bitfinex.recruitee.com",  "https://www.bitfinex.com",
                        "Exchange"),
            CompanyItem("binance", "https://www.binance.com/en/careers/job-openings",
                        "https://www.binance.com", "Exchange"),
            CompanyItem("coinmarketcap", "https://careers.smartrecruiters.com/B6/coinmarketcap",
                        "https://coinmarketcap.com", "Information"),
            CompanyItem("trustwallet", "https://careers.smartrecruiters.com/B6/trustwallet",
                        "https://trustwallet.com", "Wallet"),
            CompanyItem('syndica', 'https://jobs.ashbyhq.com/syndica',  'https://www.sygnum.com',
                        'Crypto bank'),
            CompanyItem('ellipsislabs', 'https://jobs.ashbyhq.com/ellipsislabs',
                        'https://ellipsislabs.xyz', 'Trading Protocol'),
            CompanyItem("Swissquote", "https://careers.smartrecruiters.com/Swissquote",
                        "https://en.swissquote.com", "Exchange"),
            CompanyItem("Coinshift", "https://jobs.lever.co/Coinshift",  "https://coinshift.xyz",
                        "Custody software"),
            CompanyItem("swissborg", "https://jobs.lever.co/swissborg",  "https://swissborg.com",
                        "Exchange"),
            CompanyItem("OpenSea", "https://jobs.lever.co/OpenSea",
                        "https://opensea.io", "NFT"),
            CompanyItem("storyprotocol", "https://jobs.lever.co/storyprotocol",
                        "https://www.storyprotocol.xyz", "Protocol"),
            CompanyItem("ethereumfoundation", "https://jobs.lever.co/ethereumfoundation",
                        "https://ethereum.org", "Blockchain"),
            CompanyItem("aave", "https://jobs.eu.lever.co/aave",
                        "https://aave.com", "Protocol"),
            CompanyItem("crypto", "https://jobs.lever.co/crypto",
                        "https://crypto.com", "Exchange"),
            CompanyItem("Luxor", "https://jobs.lever.co/LuxorTechnology",  "https://www.luxor.tech",
                        "Mining"),
            CompanyItem("anchorage", "https://jobs.lever.co/anchorage",  "https://www.anchorage.com",
                        "Trading"),
            CompanyItem("biconomy", "https://jobs.lever.co/biconomy",  "https://www.biconomy.io",
                        "Infra"),
            CompanyItem("avalabs", "https://boards.greenhouse.io/avalabs",
                        "https://www.avalabs.org", "Blockchain"),
            CompanyItem("Polygon", "https://jobs.lever.co/Polygon",  "https://polygon.technology",
                        "Blockchain"),
            CompanyItem("tokenmetrics", "https://jobs.lever.co/tokenmetrics",
                        "https://www.tokenmetrics.com", "Information"),
            CompanyItem("offchainlabs", "https://jobs.lever.co/offchainlabs",
                        "https://offchainlabs.com", "Protocol"),
            CompanyItem("subspacelabs", "https://jobs.lever.co/subspacelabs",
                        "https://subspace.network", "Blockchain Infra"),
            CompanyItem("tron", "https://boards.greenhouse.io/rainberry",  "https://tron.network",
                        "Blockchain"),
            CompanyItem("messari", "https://boards.greenhouse.io/messari",  "https://messari.io",
                        "Information"),
            CompanyItem("copperco", "https://boards.eu.greenhouse.io/copperco",
                        "https://copper.co", "Custody"),
            CompanyItem("digitalasset", "https://boards.greenhouse.io/digitalasset",
                        "https://www.digitalasset.com", "Custody"),
            CompanyItem("ramp.network", "https://jobs.lever.co/careers.ramp.network",
                        "https://ramp.network", "Payments"),
            CompanyItem('risklabs', 'https://jobs.lever.co/risklabs',  'https://risklabs.foundation',
                        'Protocol'),
            CompanyItem("ledger", "https://jobs.lever.co/ledger",
                        "https://www.ledger.com", "Wallet"),
            CompanyItem("layerzerolabs", "https://boards.greenhouse.io/layerzerolabs",
                        "https://layerzero.network", "Infra"),
            CompanyItem("request", "https://jobs.lever.co/request",  "https://request.network",
                        "Payments"),
            CompanyItem('okcoin', 'https://boards.greenhouse.io/okcoin',
                        'https://www.okcoin.com', 'Exchange'),
            CompanyItem("immutable", "https://jobs.lever.co/immutable",  "https://www.immutable.com",
                        "NFT"),
            CompanyItem("web3auth", "https://jobs.lever.co/TorusLabs",
                        "https://web3auth.io", "Auth"),
            CompanyItem("jumpcrypto", "https://boards.greenhouse.io/jumpcrypto",
                        "https://jumpcrypto.com", "Infra"),
            CompanyItem("oasisnetwork", "https://boards.greenhouse.io/oasisnetwork",
                        "https://oasisprotocol.org", "Protocol"),
            CompanyItem("consensys", "https://consensys.net/open-roles", "https://consensys.net",
                        "Infra"),
            CompanyItem("poap", "https://boards.greenhouse.io/poaptheproofofattendanceprotocol",
                        "https://poap.xyz", "Protocol"),
            CompanyItem("chainsafesystems", "https://boards.greenhouse.io/chainsafesystems",
                        "https://chainsafe.io", "Infra"),
            CompanyItem("ripple", "https://ripple.com/careers/all-jobs", "https://ripple.com",
                        "Blockchain"),
            CompanyItem("kadena", "https://boards.greenhouse.io/kadenallc",  "https://kadena.io",
                        "Blockchain"),
            CompanyItem("eigenlabs", "https://boards.greenhouse.io/eigenlabs",
                        "https://www.eigenlayer.xyz", "Infra"),
            CompanyItem("cere-network", "https://jobs.lever.co/cere-network",  "https://cere.network",
                        "Infra"),
            CompanyItem('sygnum', 'https://sygnum.bamboohr.com/careers',  'https://www.sygnum.com',
                        'Crypto bank'),
            CompanyItem('matterlabs', 'https://jobs.eu.lever.co/matterlabs',  'https://matter-labs.io',
                        'Protocol'),
            CompanyItem('iofinnet', 'https://iofinnethr.bamboohr.com/jobs/?source=bamboohr',
                        'https://www.iofinnet.com', 'Custody'),
            CompanyItem("galaxydigitalservices", "https://boards.greenhouse.io/galaxydigitalservices",
                        "https://www.galaxy.com", 'Trading'),
            CompanyItem("hiro", "https://jobs.lever.co/hiro",
                        "https://www.hiro.so", "Infra"),
            CompanyItem('web3', 'https://web3.bamboohr.com/jobs',  'https://web3.foundation',
                        'web3'),
            CompanyItem('dappradar', 'https://dappradar.bamboohr.com/careers',
                        'https://dappradar.com', 'Exchange & NFT'),
            CompanyItem("solanafoundation", "https://jobs.ashbyhq.com/Solana%20Foundation",
                        "https://solana.org", "Blockchain"),
            CompanyItem("solana", "https://boards.greenhouse.io/solana",
                        "https://solana.com", "Blockchain"),
            CompanyItem('mobilecoin', 'https://boards.greenhouse.io/mobilecoin',
                        'https://mobilecoin.com', 'Blockchain'),
            CompanyItem('chia', 'https://www.chia.net/careers',
                        'https://www.chia.net', 'Blockchain'),
            CompanyItem("worldcoin", "https://boards.greenhouse.io/worldcoinorg",
                        "https://worldcoin.org", "Blockchain"),
            CompanyItem("edgeandnode", "https://boards.greenhouse.io/edgeandnode",
                        "https://edgeandnode.com", "Infra"),
            CompanyItem("clearmatics", "https://boards.greenhouse.io/clearmatics",
                        "https://www.clearmatics.com", "Protocol"),
            CompanyItem('bitstamp', 'https://apply.workable.com/bitstamp/#jobs',
                        'https://www.bitstamp.net', 'Exchange'),
            CompanyItem('AQX', 'https://jobs.lever.co/AQX',
                        'https://aqx.com', 'Exchange and Web3'),
            CompanyItem('smart-token-labs', 'https://apply.workable.com/smart-token-labs',
                        'https://smarttokenlabs.com', 'Web3 bridge'),
            CompanyItem('avantgarde', 'https://apply.workable.com/avantgarde',
                        'https://avantgarde.finance', 'Asset Management'),
            CompanyItem('stably', 'https://apply.workable.com/stably',  'https://stably.io',
                        'Stable Coin'),
            CompanyItem('bitwise', 'https://jobs.lever.co/bitwiseinvestments',
                        'https://bitwiseinvestments.com', 'Asset Management'),
            CompanyItem('cryptofinance', 'https://apply.workable.com/cryptofinance',
                        'https://www.crypto-finance.com', 'Exchange'),
            CompanyItem('bitget', 'https://apply.workable.com/bitget',  'https://www.bitget.com/en',
                        'Exchange')]


def build_img_tag(name):
    return f'<img src="resources/{name}.png" alt="{name.title()}" loading="lazy" width="188" height: auto >'


def get_logo(company_name):
    company_logos = [
        'wintermute',
        'mobilecoin',
        'tether',
        'paradigm.com',
        'paradigm.xyz',
        'dune',
        'bitfury',
        'archblock',
        '0x',
        'chia',
        'AQX',
        'kraken',
        'ethglobal',
        'harmony',
        'bebop',
        'chainstack',
        'chainlink',
        'axiomzen',
        'bitwise',
        'tessera',
        'paxos',
        'eigenlabs',
        'bitcoin',
        'binance',
        'bitget',
        'stably',
        'bitstamp',
        'consensys',
        'ripple',
        'aztec',
        'stellar',
        'sygnum',
        'okcoin',
        'matterlabs',
        'clearmatics',
        'worldcoin',
        'edgeandnode',
        'risklabs',
        'circle',
        'bittrex',
        'kaiko',
        'hiro',
        'avalabs',
        'Polygon',
        'multiversx',
        'status',
        'cexio',
        'dappradar',
        'web3',
        'smart-token-labs',
        'avantgarde',
        'cryptofinance',
        'Luxor',
        'anchorage',
        'biconomy',
        'solanafoundation',
        'fuellabs'
    ]
    if company_name in company_logos:
        return build_img_tag(company_name)
    return company_name.upper()
