name: Build Web page

on:
  schedule:
    - cron: '0 9 * * *'
  workflow_dispatch:

permissions:
  contents: write
  pull-requests: write

jobs:
  run-crawler:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python 3.12
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install dependencies
        run: |
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

      - name: Run site_builder.py
        run: python site_builder.py

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v6
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: 'chore: update Web [automated]'
          base: main
          branch: 'auto/crawler-update'
          title: 'Automated update from site_builder.py'
          body: 'This PR contains changes made by running site_builder.py via GitHub Actions.'
          delete-branch: true
          reviewers: yury-dubinin
